# Generated by Django 5.0.2 on 2024-03-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_CadUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
